QB-6: Create Footer
mehedihassandev/quickbuy pull request #8
Opened 2024-04-25 12:21 UTC by sun-mit

-Create Footer

2024-04-25 15:04 UTC, mehedihassandev requested changes
rc

2024-04-25 15:46 UTC, sun-mit commented on src/app/components/Footer/index.tsx
> +      <Box sx={{ ml: "20rem", mr: "10rem", maxWidth: "lg" }}>
why ? explain please @mehedihassandev

2024-04-26 03:51 UTC, mehedihassandev commented on src/app/components/Footer/index.tsx
> +      <Box sx={{ ml: "20rem", mr: "10rem", maxWidth: "lg" }}>
we are using the same container size everywhere. if we don't use the same container size in every component then it will break our app design

2024-04-26 04:35 UTC, sun-mit commented on src/app/components/Footer/index.tsx
> +      <Box sx={{ ml: "20rem", mr: "10rem", maxWidth: "lg" }}>
resolved

2024-04-26 05:36 UTC, mehedihassandev approved these changes

2024-04-26 05:36 UTC, merged