Add bestselling section
mehedihassandev/quickbuy pull request #9
Opened 2024-04-25 12:59 UTC by paul-111

Adding Best Seller section 

![image](https://github.com/mehedihassandev/quickbuy/assets/67852481/dcd81d84-f3c5-41b0-b035-4491967246af)

2024-04-25 14:58 UTC, mehedihassandev commented on src/app/components/pages/Products/index.tsx
> +        style={{ display: "flex", flexDirection: "row", gap: 15 }}
use sx

2024-04-25 15:02 UTC, mehedihassandev requested changes
RC

2024-04-25 15:49 UTC, sun-mit commented on src/assets/img/vase1.avif
why we use .avif ? I think svg/png good idea.

2024-04-25 16:08 UTC, sun-mit commented on src/app/components/dummy/best-seller.tsx
> +export const productDummyData = [
good one to make dummy

2024-04-26 04:13 UTC, paul-111 commented on src/assets/img/vase1.avif
avif was original extension actually and didn't change once got saved, i can change it though, will update then

2024-04-30 12:58 UTC, mehedihassandev commented
resolve conflicts ASAP @paul-111

2024-04-30 12:58 UTC, paul-111 commented
@mehedihassandev aii chup

2024-05-01 11:15 UTC, mehedihassandev approved these changes

2024-05-01 11:16 UTC, merged